# Generated by Django 5.2.8 on 2025-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_record', '0002_category_type_alter_category_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.RemoveField(
            model_name='record',
            name='type',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
