# Generated by Django 5.2.8 on 2025-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_record', '0003_remove_record_category_remove_record_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
