# Generated by Django 5.2.8 on 2025-11-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_record', '0004_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dds_record.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dds_record.subcategory'),
            preserve_default=False,
        ),
    ]
